### PR TITLE
Build with icu

### PR DESCRIPTION
**Pull request by steveisok**
Repos who consume the node transport package seem to need icu support, so enable.

### CODE REVIEW

**Comment by akoeplinger** [comment]
did you check the size increase? there is also a `small-icu` option that might be enough for us since it supports the RegExp: https://nodejs.org/api/intl.html#options-for-building-nodejs

**Comment by akoeplinger** [comment]
Looks like the win arm64 build is failing:
>    icutrim
    '..\..\artifacts\obj\node\Release\icupkg' is not recognized as an internal or external command,
    operable program or batch file.
    Options: {'toolpath': '..\\..\\artifacts\\obj\\node\\Release\\', 'datfile': '../../deps/icu-tmp/icudt73l.dat', 'filterfile': 'icu_small.json', 'tmpdir': '..\\..\\artifacts\\obj\\node\\Release\\obj/global_intermediate/icutmp', 'deltmpdir': 1, 'outfile': 'icudt73l.dat', 'verbose': 1, 'locales': 'en,root', 'endian': 'little'}
    icu_small.json: icutrim.py config: Trim down ICU to just a certain locale set, needed for node.js use.
    FAILED: ..\..\artifacts\obj\node\Release\icupkg -tl ../../deps/icu-tmp/icudt73l.dat ..\..\artifacts\obj\node\Release\obj/global_intermediate/icutmp\icudt73l.dat
  C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(254,5): error MSB8066: Custom build for '..\..\deps\icu-tmp\icudt73l.dat;..\..\artifacts\obj\node\Release\\obj\global_intermediate\icutmp\icudt73l.dat' exited with code 1. [D:\a\_work\1\s\tools\icu\icudata.vcxproj]

Maybe we're missing python?

**Comment by lewing** [comment]
@ilonatommy is icupkg part of icu or something specific to node?

cc @radekdoulik

**Comment by akoeplinger** [comment]
I think it is here: https://github.com/dotnet/node/tree/dotnet/main/deps/icu-small/source/tools/icupkg

**Comment by akoeplinger** [comment]
I think I know what's going on:

The x64 build has this:
```
     icupkg.vcxproj -> ..\..\artifacts\obj\node\Release\\icupkg.exe
```

while the arm64 one has this:

```
   icupkg_host.vcxproj -> ..\..\artifacts\obj\node\Release\\icupkg_host.exe
```

so basically it's building for the (x64) host which makes sense, so we likely just need a tweak in the script that's calling the tool.

**Review by akoeplinger — APPROVED** [review]

**Comment by akoeplinger** [comment]
I pushed a workaround, turns out gyp does some magic with the paths so `<(PRODUCT_DIR)/icupkg<(EXECUTABLE_SUFFIX)` is either icupkg.exe or icupkg_host.exe, we can just pass that to the script.

**Pull request merged**
